trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ./auto/lint
  displayName: 'eslint'

- script: ./auto/test
  displayName: 'test'

- script: ./auto/release
  displayName: 'Release'
