trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ./auto/lint
  displayName: 'eslint'

- script: ./auto/test
  displayName: 'test'


- task: Docker@2
  inputs:
    containerRegistry: 'docker-hub'
    command: 'login'

- script: ./auto/release
  displayName: 'Release'
