trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ./auto/lint
  displayName: 'eslint'

- script: ./auto/test
  displayName: 'test'

- script: ./auto/compile
  displayName: 'Compile'

- task: Docker@2
  inputs:
    containerRegistry: 'docker-hub'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
