#!/bin/bash -eu

cd $(dirname $0)/..

function semverParseInto() {
    local RE='[^0-9]*\([0-9]*\)[.]\([0-9]*\)[.]\([0-9]*\)\([0-9A-Za-z-]*\)'
    #MAJOR
    eval $2=`echo $1 | sed -e "s#$RE#\1#"`
    #MINOR
    eval $3=`echo $1 | sed -e "s#$RE#\2#"`
    #MINOR
    eval $4=`echo $1 | sed -e "s#$RE#\3#"`
    #SPECIAL
    eval $5=`echo $1 | sed -e "s#$RE#\4#"`
}

VERSION=$(cat version.txt)
IMAGE="chengqingsu/hello-world-express"

auto/compile

semverParseInto $VERSION MAJOR MINOR PATCH SPECIAL

docker build . -t "${IMAGE}:latest"
docker push "${IMAGE}:latest"

docker tag "${IMAGE}:latest" "${IMAGE}:${MAJOR}"
docker push "${IMAGE}:${MAJOR}"

docker tag "${IMAGE}:latest" "${IMAGE}:${MAJOR}.${MINOR}"
docker push "${IMAGE}:${MAJOR}.${MINOR}"

docker tag "${IMAGE}:latest" "${IMAGE}:${MAJOR}.${MINOR}.${PATCH}"
docker push "${IMAGE}:${MAJOR}.${MINOR}.${PATCH}"
